### ISSUE TITLE
transfer to JuliaIO org?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaIO/CodecLz4.jl#29]
Now that all the other CodecX packages have been moved to the [JuliaIO](https://julialang.org/learning/) org, would it make sense to transfer this one there as well? If Invenia wants to add a little note in the README to indicate that it was developed there, that would be ok (in addition to the LICENSE, which already indicates that).

**Comment by omus** [comment]
We're onboard with transferring the package to the JuliaIO org. Currently it appears that no one at Invenia has access to that org so we can either grant ownership to this repo or one of us will need access to JuliaIO.

**Comment by StefanKarpinski** [comment]
Great. @omus, I've added you as a member of JuliaIO. Anyone else who's willing to help maintain these packages, just let me know.

**Comment by omus** [comment]
Sounds good. We'll get the CI issue sorted out first and then we'll do the migration

**Comment by morris25** [comment]
I'd be willing to help with JuliaIO maintenance as well.

**Comment by StefanKarpinski** [comment]
Ok, you both have pending invites to JuliaIO that need to be accepted before you can transfer.

**Comment by omus** [comment]
Repo has been moved. Just need to do some cleanup

**Comment by omus** [comment]
@StefanKarpinski could @morris25 and I get admin access on this repo? I seem to be unable to merge to master.

**Comment by StefanKarpinski** [comment]
You and @morris25 should both be admins now (Sam already was).
