### ISSUE TITLE
Document is still v0.3 but registered v0.4

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaIO/CodecLz4.jl#32]

**Comment by omus** [comment]
I'm not clear on what you mean by "document" but you are correct that v0.4.0 was successfully registered and v0.3.0 is the last release for this repo. Tagging is supposed to be handled by the TagBot action and it seems that actions were not enabled for this repo. I've corrected that and hopefully we see a tag at the next hour.

**Comment by omus** [comment]
TagBot won't tag this version without intervention. I'll hold off on tagging for now until I get some feedback on: https://github.com/JuliaRegistries/TagBot/issues/148

**Comment by omus** [comment]
I've used TagBot's manual CLI tagging feature to address this:
```bash
docker run --rm degraafc/tagbot python -m tagbot.local --repo JuliaIO/CodecLz4.jl --version v0.4.0 --token ...
```
