### ISSUE TITLE
Unable to pass LZ4FrameCompressor instance to transcode

### ISSUE THREAD

**Issue by quinnj** [JuliaIO/CodecLz4.jl#33]
Should this work? It seems to be supported by other codecs:
```julia
julia> transcode(LZ4FrameCompressor(; compressionlevel=4), bytes)
ERROR: LZ4F_cctx: Uninitialized compression context
Stacktrace:
 [1] transcode(codec::LZ4FrameCompressor, data::Vector{UInt8})
   @ TranscodingStreams ~/.julia/packages/TranscodingStreams/MsN8d/src/transcode.jl:121
 [2] top-level scope
   @ REPL[93]:1
```
Is there another (better?) way to compress a `Vector{UInt8}` at a user-provided compression level?

**Comment by iamed2** [comment]
I found this confusing as well; apparently you need to initialize the compressor before calling `transcode`: https://juliaio.github.io/TranscodingStreams.jl/latest/reference/#Base.transcode-Tuple{TranscodingStreams.Codec,Union{Array{UInt8,1},%20CodeUnits{UInt8,S}%20where%20S%3C:AbstractString}}

**Comment by quinnj** [comment]
Thanks @iamed2; I agree it's a bit confusing, but this at least solves my immediate issue.
